### ISSUE TITLE
Experimental results on ImageNet

### ISSUE THREAD

**Issue by yjh576** [jameelhassan/PromptAlign#11]
Is this code compatible with the ImageNet dataset? I noticed that the paper does not report any experimental results on ImageNet, but I want to obtain the results on ImageNet. Could you provide me with some advice?

**Comment by jameelhassan** [comment]
The Multimodal prompts are trained on ImageNet. Since the method is a test-time adaptation technique, using this to evaluate on ImageNet (the same distribution) is not in line with the problem setting.
