### ISSUE TITLE
About Proxy source dataset (imagenet)

### ISSUE THREAD

**Issue by Git-L1** [jameelhassan/PromptAlign#12]
This is a very good job! I have some questions to ask, do you use train, val, or test for the proxy dataset imagenet? And was it ultimately calculated offline through the vit-b-16 model?
Looking forward to your early reply, thank you!

**Comment by jameelhassan** [comment]
Hi,
The train set of Imagenet was used as the proxy source dataset. It was calculated offline using the ViT-B/16 model with multimodal prompts from the [MaPLe](https://arxiv.org/abs/2210.03117) method.

**Comment by Git-L1** [comment]
ok, Thank you very much!
