### ISSUE TITLE
Can provide the mean and variance of the imagenet's feature, for running the function save_feature_maps in the test function error, res.visual_feature is empty

### ISSUE THREAD

**Issue by YTyangting** [jameelhassan/PromptAlign#14]

**Comment by jameelhassan** [comment]
Hi,

The source dataset statistics are provided here https://github.com/jameelhassan/PromptAlign/blob/master/docs/run.md#config-file-settings. You do not need to run and compute this separately.

**Comment by YTyangting** [comment]
Thank you very much, I didn't notice the file.
