### ISSUE TITLE
Where to download ImgNetpre_vis_means.pt and ImgNetpre_vis_vars.pt?

### ISSUE THREAD

**Issue by vellichorw** [jameelhassan/PromptAlign#2]
Thanks for the code! I encountered a 'FileNotFoundError' for './output/features/ImgNetpre_vis_vars.pt'. The '.pt' files are not in the repo.  Where can I get 'ImgNetpre_vis_means.pt' and 'ImgNetpre_vis_vars.pt'?

**Comment by jameelhassan** [comment]
Hi, Please check the run.md [here](https://github.com/jameelhassan/PromptAlign/blob/master/docs/run.md). That should solve the problem.
