### ISSUE TITLE
Could you release dassl.utils.tpt_tools file?

### ISSUE THREAD

**Issue by YunYunY** [jameelhassan/PromptAlign#3]
Dear authors,

Thank you for sharing the code. Coud you please release the file dassl.utils.tpt_tools? It looks like this is a customer modification for tpt specifically. 

Thank you very much.

**Comment by AlyssaYoung** [comment]
Have you solved this problem?

**Comment by YunYunY** [comment]
> Have you solved this problem?

Yes replace the import path with code from here https://github.com/azshue/TPT/blob/main/utils/tools.py

**Comment by AlyssaYoung** [comment]
Thanks a lot. It does work!
