### ISSUE TITLE
Can you release Offline statistics code?

### ISSUE THREAD

**Issue by YunYunY** [jameelhassan/PromptAlign#5]
Thank you. I'd like to see which part of the data is used and how to deal with the running variance estimation.

**Comment by jameelhassan** [comment]
Hi, 
We dont have a separate script for this. We use the inference script to perform the forward pass to compute the statistics. Two passes of the dataset(imagenet) is performed, first to calculate the means, and the next to calculate the variances using the means that were calculated. So there is no running variance estimation.

The features are stored in the ResBlock as in https://github.com/jameelhassan/PromptAlign/blob/929056429ddbe9da449e7e55d3b16e267089a29c/clip/model.py#L337
and then the features are saved as in https://github.com/jameelhassan/PromptAlign/blob/929056429ddbe9da449e7e55d3b16e267089a29c/trainers/prompt_align.py#L526

Note that the function needs to be modified to save the variances after the means are saved.

**Comment by AlyssaYoung** [comment]
Hi,
I have some questions about the  save_feature_maps function:
https://github.com/jameelhassan/PromptAlign/blob/929056429ddbe9da449e7e55d3b16e267089a29c/trainers/prompt_align.py#L532-L535
The visual_feats vector is the visual features saved for the current batch in the forward pass. Why is it divided by the size of the dataset?

**Comment by jameelhassan** [comment]
Hi,

A minor clarification to be made here. The self.visual_feat attribute is only used for the alignment at test time here. 

However, to compute the offline statistics, we carry the running sum (not shown in the code). This is then divided by the number of samples in the dataset. 

Something like;
For means
self.visual_feat = torch.cat(torch.sum(self.visual_feat), x)

For variances, use the computed means
self.visual_feat = torch.cat(torch.sum((x - self.mean) ** 2), self.visual_feat)

**Comment by tinybitdesu** [comment]
Hi, I have some questions to ask, same in save_feature_maps functions.
If I run save_feature_maps functions in release code, could I get the same source data statistics ImgNet_vis_means.pt as your google drive releases? Or this part is not shown in the code? If not shown, could you give some tips for collecting these  data statistics?

**Comment by jameelhassan** [comment]
Hi, the statistics computation code is not provided separately. 
You need to run the forward pass twice as mentioned in the comment above. But you need to modify the features saved to compute the variance if it is originally storing the means. 

If you simply run our code, you will not get the statistics you want. But with the minor edits to the code you should get the exact same statistics.
