### ISSUE TITLE
About the checkpoint of MaPle.

### ISSUE THREAD

**Issue by bugwriterLee** [jameelhassan/PromptAlign#6]
Thanks for sharing the code! But I failed to find the file "weights/maple/ori/seed1/MultiModalPromptLearner/model.pth.tar-2", where can I find it? Thanks for your answer!

**Comment by jameelhassan** [comment]
Hi,
Please use the weights of MaPLe from https://github.com/muzairkhattak/multimodal-prompt-learning?tab=readme-ov-file#model-zoo

These weights https://drive.google.com/drive/folders/18ISKsjc18e19Ov2nXOuH228FYBtgUa1O

We will add this to the documentation. Thanks.
